name: Run Unit Tests
on:
  push:
    branches:
      - '*'

jobs:
  build-and-run-unit-tests:
    runs-on: any_archLinux
    steps:
      - run: git clone --depth=1 --no-single-branch https://git.seodisparate.com/stephenseo/SimpleArchiver.git simplearchiver
        name: Get repo
      - run: cd simplearchiver && git checkout "${GITHUB_REF_NAME}"
        name: Checkout the branch
      - run: cmake -S simplearchiver -B buildDebug
        name: Run cmake to prepare the build
      - run: make -C buildDebug
        name: Build
      - run: ./buildDebug/test_datastructures
        name: Run test_datastructures
